[package]
name = "phosphor"
version = "0.1.0"
authors = ["<locke9@gmail.com>"]
edition = "2018"

description = """
A path tracer written in Rust
"""

[dependencies]
cgmath = { version = "0.17", features = ["serde"] }
approx = "0.3"
log = "0.4"
fern = "0.5"
rand = "0.6"
rand_pcg = "0.1"
image = "0.22"
num-traits = "0.2"
# tobj = "0.1"
vec_map = "0.8"
rayon = "1"
serde = "1.0.46"
serde_json = "1"
serde_derive = "1.0"
# bincode = "1.0"

embree = { path = "../embree-rs" }

# ultraviolet = "0.4"

# bytemuck = "1"
# indicatif = "0.13"

# state = "0.4"
# spa = "0.2"

[profile.dev]
opt-level = 2

# Set the default for dependencies.
# [profile.dev.package."*"]
# opt-level = 2

#[profile.release]
#panic = 'abort'
#codegen-units = 1
#lto = true
#lto = "thin"
#opt-level = "z"
#debug = 1 # Line numbers only

[profile.release.build-override]
opt-level = 0