[package]
name = "phosphor"
version = "0.1.0"
authors = ["<locke9@gmail.com>"]
edition = "2018"

description = """
A path tracer written in Rust
"""

[dependencies]
cgmath = { version = "0.16", features = ["serde"] }
approx = "0.1.1"
log = "0.4"
fern = "0.5"
rand = "0.6"
rand_pcg = "0.1"
image = "0.20"
num-traits = "0.1.43"
tobj = "0.1.6"
vec_map = "0.8"
rayon = "1"
serde = "1.0.46"
serde_json = "1"
serde_derive = "1.0"
# bincode = "1.0"
# state = "0.4"
embree = { path = "../embree-rs" }

# noisy_float = "0.1"
# derive_more = "0.10"

[profile.dev]
opt-level = 2

#[profile.release]
#panic = 'abort'
#codegen-units = 1
#lto = true
#debug = true