[package]
name = "scene_import"
version = "0.1.0"
authors = ["Steven <locke9@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.46", features = ["derive"] }
serde_json = "1"
bincode = "1"
tobj = { version = "2", features = ["log"] }
glam = "0.11"
# bytemuck = "1.4"
